version: '3'
services:
  server:
    build: .
    ports:
     - "443:443"
  oracledb:
    image: "oracle/database:11.2.0.2-xe"
    shm_size: 1g
    volumes:       
      - ./db-data:/u01/app/oracle/oradata
    env_file:
      - .env
