CREATE TABLE user_profile (
  id            INT GENERATED BY DEFAULT ON NULL AS IDENTITY,
  email         VARCHAR(100) UNIQUE,
  password_hash CHAR(32) NOT NULL,
  created_at    TIMESTAMP DEFAULT current_timestamp,
  updated_at    TIMESTAMP DEFAULT current_timestamp
);

