CREATE TABLE reminder (
  id         INT GENERATED BY DEFAULT ON NULL AS IDENTITY,
  title      VARCHAR(1000) NOT NULL,
  display_at TIMESTAMP     NOT NULL,
  created_at TIMESTAMP DEFAULT current_timestamp,
  updated_at TIMESTAMP DEFAULT current_timestamp
);

