package data

import (
	migrate "github.com/rubenv/sql-migrate"
)

func GetMigrations() *migrate.MemoryMigrationSource {
	return &migrate.MemoryMigrationSource{
		Migrations: []*migrate.Migration{
			{
				Id: "1",
				Up: []string{`
CREATE TABLE user_profile (
  id            INT GENERATED BY DEFAULT ON NULL AS IDENTITY,
  email         VARCHAR(100) UNIQUE,
  password_hash CHAR(32) NOT NULL,
  created_at    TIMESTAMP DEFAULT current_timestamp,
  updated_at    TIMESTAMP DEFAULT current_timestamp
);
				`},
				Down: []string{`
DROP TABLE user_profile;
				`},
			},
			{
				Id: "2",
				Up: []string{`
CREATE TABLE user_profile (
  id            INT GENERATED BY DEFAULT ON NULL AS IDENTITY,
  email         VARCHAR(100) UNIQUE,
  password_hash CHAR(32) NOT NULL,
  created_at    TIMESTAMP DEFAULT current_timestamp,
  updated_at    TIMESTAMP DEFAULT current_timestamp
);
				`},
				Down: []string{`
DROP TABLE note;
				`},
			},
			{
				Id: "3",
				Up: []string{`
CREATE TABLE reminder (
  id         INT GENERATED BY DEFAULT ON NULL AS IDENTITY,
  title      VARCHAR(1000) NOT NULL,
  display_at TIMESTAMP     NOT NULL,
  created_at TIMESTAMP DEFAULT current_timestamp,
  updated_at TIMESTAMP DEFAULT current_timestamp
);
				`},
				Down: []string{`
DROP TABLE reminder;
				`},
			},
			{
				Id: "4",
				Up: []string{`
CREATE TABLE device (
  user_id           INT NOT NULL,
  device_identifier VARCHAR(100) UNIQUE,
  FOREIGN KEY (user_id) REFERENCES user_profile (id),
  PRIMARY KEY (user_id, device_identifier)
);
				`},
				Down: []string{`
DROP TABLE device;
				`},
			},
		},
	}
}
