CREATE TABLE user_profile (
  id            INT GENERATED BY DEFAULT ON NULL AS IDENTITY,
  email         VARCHAR(100) UNIQUE,
  password_hash CHAR(32) NOT NULL,
  created_at    TIMESTAMP DEFAULT current_timestamp,
  updated_at    TIMESTAMP DEFAULT current_timestamp
);

CREATE TABLE note (
  id         INT GENERATED BY DEFAULT ON NULL AS IDENTITY,
  title      VARCHAR(100) NOT NULL,
  body       BLOB         NOT NULL,
  created_at TIMESTAMP DEFAULT current_timestamp,
  updated_at TIMESTAMP DEFAULT current_timestamp
);

CREATE TABLE reminder (
  id         INT GENERATED BY DEFAULT ON NULL AS IDENTITY,
  title      VARCHAR(1000) NOT NULL,
  display_at TIMESTAMP     NOT NULL,
  created_at TIMESTAMP DEFAULT current_timestamp,
  updated_at TIMESTAMP DEFAULT current_timestamp
);

CREATE TABLE device (
  user_id           INT NOT NULL,
  device_identifier VARCHAR(100) UNIQUE,
  FOREIGN KEY (user_id) REFERENCES user_profile (id),
  PRIMARY KEY (user_id, device_identifier)
);

